import { cx } from 'class-variance-authority';
import type { Metadata } from 'next';
import { Alex_Brush, Noto_Serif } from 'next/font/google';
import './globals.css';

const playfair_display = Noto_Serif({
  subsets: ['vietnamese'],
  variable: '--font-playfair-display',
});

const alex_brush = Alex_Brush({
  subsets: ['vietnamese'],
  variable: '--font-dancing-script',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Thiệp mời',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cx(
          'font-light leading-[2]',
          playfair_display.variable,
          alex_brush.variable,
          playfair_display.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
